# Site settings and string variables
title: "Digital Toolkit"
nav-trigger-text: "Select Navigation"
contribute-link-text: "Contribute on GitHub"
steps-name-text: "Good Practices"
contribute-link: "https://github.com/bcgov/innovation-toolkit/wiki/Contributing-to-the-Digital-Toolkit"

# Site description
description: "This toolkit offers a set of steps that can be followed when developing a digital service inside (or outside) the British Columbia Public Service."

# Site emails and contacts
main-email: "bcdevexchange@gov.bc.ca"
feedback-email: "jim.rabb@gov.bc.ca"

# Site paths - set these in production!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://innovation-toolkit.pathfinder.bcgov" # the base hostname & protocol for your site

# Excerpt the first sentence and use that for the .excerpt
# Alternatively, we could pipe the excerpt to | truncatewords:75
excerpt_separator: .

# Build settings
markdown: kramdown

# URL settings
permalink: pretty

# Collections
collections:
  practices:
    output: true
    permalink: /practices/:path/
  in-practice-examples:
    output: true
    permalink: /in-practice-examples/:name/
  guides:
    output: true
    permalink: /guides/:path/

# Defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "steps"
    values:
      layout: "step"
  -
    scope:
      type: "in-practice-examples"
    values:
      layout: "example"
  -
    scope:
      type: "guides"
    values:
      layout: "guide"
# -
#   scope:
#     path: "projectz" # glob patterns are possible: https://jekyllrb.com/docs/configuration/#glob-patterns-in-front-matter-defaults
#     type: "pages" # can be: pages, posts, drafts or any collection name in your site
#   values:
#     layout: "step" # overrides any previously declared default layout
#     author: "Mr. Hyde" # custom vars are possible too! :)

# Exclude these from processing.
# Do not remove.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - src
  - workfiles
  - NOTES
  - CONTRIBUTING.md
  - CODE OF CONDUCT.md
  - LICENCE
  - README.md
  - webpack.config.js
  - sync-local-dev.bash # workfile that syncs local to dev site
